apiVersion: v1
kind: Service
metadata:
  name: test_graphql
spec:
  selector:
    app: test_graphql
    tier: backend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test_graphql
    tier: backend
  name: test_graphql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test_graphql
        tier: backend
    spec:
      containers:
        - image: '{{.image}}'
          # imagePullPolicy: IfNotPresent
          name: test_graphql
          ports:
            - containerPort: 3000
              protocol: TCP
      terminationGracePeriodSeconds: 30
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
