steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - source
      - repos
      - clone
      - github_nickhsine_kubernetes-configs
      - ./dockerignore/kubernetes-configs
  - name: bash
    args:
      - cp
      - ./dockerignore/kubernetes-configs/openwarehouse/overlays/dev/overlays/tv/overlays/cms/configs/config.js
      - ./configs/config.js
  - name: bash
    args:
      - cp
      - ./dockerignore/kubernetes-configs/openwarehouse/base/configs/gcskeyfile.json
      - ./configs/gcskeyfile.json
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/${PROJECT_ID}/openwarehouse:${BRANCH_NAME}_${SHORT_SHA}'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/openwarehouse

  # NOTICE: THE FOLLOWING STEPS ARE FOR TEMPRARY USAGE
  # build `kustomize` configs
  - name: 'launcher.gcr.io/google/ubuntu1604'
    entrypoint: bash
    args:
      - '-c'
      - |
        # install kustomize
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

        # mv kubernetes-configs folder
        mv ./dockerignore/kubernetes-configs /workspace/kubernetes-configs

        # cd to dev environment kustimzation root
        cd /workspace/kubernetes-configs/openwarehouse/overlays/${BRANCH_NAME}/base

        # update docker image
        /workspace/kustomize edit set image openwarehouse=gcr.io/${PROJECT_ID}/openwarehouse:${BRANCH_NAME}_${SHORT_SHA}

        # back to kubernetes-configs root
        cd /workspace/kubernetes-configs

        /workspace/kustomize build "./openwarehouse/overlays/${BRANCH_NAME}/overlays/tv/overlays/cms" >> $_FILE_TO_DEPLOY
        echo "---" >> $_FILE_TO_DEPLOY

        /workspace/kustomize build "./openwarehouse/overlays/${BRANCH_NAME}/overlays/tv/overlays/gql-internal" >> $_FILE_TO_DEPLOY
        echo "---" >> $_FILE_TO_DEPLOY

        /workspace/kustomize build "./openwarehouse/overlays/${BRANCH_NAME}/overlays/tv/overlays/gql-external" >> $_FILE_TO_DEPLOY
        echo "---" >> $_FILE_TO_DEPLOY

        # print out configs
        cat $_FILE_TO_DEPLOY

  # deploy to kubernetes cluster by config file
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - apply
      - -f
      - $_FILE_TO_DEPLOY
        # TODO: remove --dry-run when cloudbuild ready
      - --dry-run=server
      - --validate=true
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-east1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=tv-cluster'

images:
  - gcr.io/$PROJECT_ID/openwarehouse

substitutions:
  _FILE_TO_DEPLOY: /workspace/config-to-deploy.txt # default value

timeout: 900s
